### ISSUE TITLE
these checkpoints will be available?

### ISSUE THREAD

**Issue by MaltoseFlower** [yuanzhi-zhu/SlimFlow#1]
guys, are u planning to put the checkpoints in this repo or huggingface ?

**Comment by yuanzhi-zhu** [comment]
Hey @MaltoseFlower,
Thanks for your interests in our work, we've just save some ckpts and made them public on HF
[Yuanzhi/SlimFlow · Hugging Face](https://huggingface.co/Yuanzhi/SlimFlow)
